FROM python:3

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app/instagramtools.py instagramtools.py
COPY app/telegramtools.py telegramtools.py
COPY app/InstaSub.py InstaSub.py

ENTRYPOINT ["python", "InstaSub.py", "-t", "token", "-u", "username", "-p", "password"]

